# Specify the trigger event to start the build pipeline.
# In this case, new code merged into the release branch initiates a new build.
trigger:
- release

# Specify the operating system for the Azure virtual machine running the build pipeline.
# This uses a Windows-based agent.
pool:
  name: Default

# Download the files from the designated branch in the remote Git repository
# onto the build agent.
steps:
- checkout: self
  persistCredentials: true
  clean: true

# Gather new or updated files for deployment.
# Use PowerShell to replace the Linux-specific `cp` commands with equivalent Windows commands.
- powershell: |
    $commitCount = git rev-list --count HEAD
    if ($commitCount -gt 1) {
        # If there are multiple commits, find changed files
        Write-Host "Repository has multiple commits. Performing git diff."
        $changedFiles = git diff --name-only --diff-filter=AMR HEAD~1 HEAD
        foreach ($file in $changedFiles) {
            $sourcePath = Join-Path "$(Build.Repository.LocalPath)" $file
            $destPath = Join-Path "$(Build.BinariesDirectory)" $file

            # Ensure parent directories exist
            New-Item -ItemType Directory -Path (Split-Path $destPath) -Force | Out-Null
            Copy-Item -Path $sourcePath -Destination $destPath -Force
        }
    } else {
        # First commit: Copy everything but avoid redundant directories
        Write-Host "Only one commit found. Copying all necessary files."

        Get-ChildItem -Path "$(Build.Repository.LocalPath)" -Recurse -File | ForEach-Object {
            $sourcePath = $_.FullName
            $destPath = $sourcePath -replace [regex]::Escape("$(Build.Repository.LocalPath)"), "$(Build.BinariesDirectory)"

            # Ensure directories exist before copying
            New-Item -ItemType Directory -Path (Split-Path $destPath) -Force | Out-Null
            Copy-Item -Path $sourcePath -Destination $destPath -Force
        }
    }

    # Ensure correct directory structure for Python libraries
    Write-Host "Ensuring correct directory structure for Python libraries."
    $pythonLibPathSource = "$(Build.Repository.LocalPath)\libraries\python\dabdemo\dabdemo"
    $pythonLibPathDest = "$(Build.BinariesDirectory)\libraries\python\dabdemo\dabdemo"

    New-Item -ItemType Directory -Path $pythonLibPathDest -Force | Out-Null
    Copy-Item -Path "$pythonLibPathSource\*" -Destination $pythonLibPathDest -Recurse -Force

    Copy-Item -Path "$(Build.Repository.LocalPath)\libraries\python\dabdemo\setup.py" -Destination "$(Build.BinariesDirectory)\libraries\python\dabdemo" -Force

    displayName: 'Get Changes and Copy Files'


# Create the deployment artifact and publish it.
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'DatabricksBuild'
